-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 05, 2025 at 06:26 PM
-- Wersja serwera: 10.4.32-MariaDB
-- Wersja PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `moja_strona`
--

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `page_list`
--

CREATE TABLE `page_list` (
  `id` int(11) NOT NULL,
  `page_title` varchar(255) DEFAULT NULL,
  `page_content` text DEFAULT NULL,
  `status` int(11) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `page_list`
--

INSERT INTO `page_list` (`id`, `page_title`, `page_content`, `status`) VALUES
(1, 'main.html', '<h2>Przykłady największych mostów</h2>\r\n<div class=\"gallery\">\r\n    <div class=\"bridge\">\r\n        <img src=\"./images/Danyang–Kunshan Grand Bridge.jpg\" alt=\"Danyang–Kunshan Grand Bridge\" />\r\n        <p><b>Danyang–Kunshan Grand Bridge</b>, <u>Chiny</u>, <i>164,800 m</i></p>\r\n    </div>\r\n    <div class=\"bridge\">\r\n        <img src=\"./images/Akashi Kaikyō Bridge.png\" alt=\"Akashi Kaikyō Bridge\" />\r\n        <p><b>Akashi Kaikyō Bridge</b>, <u>Japonia</u>, <i>3,911 m</i></p>\r\n    </div>\r\n    <div class=\"bridge\">\r\n        <img src=\"./images/Great Belt Bridge.jpg\" alt=\"Great Belt Bridge\" />\r\n        <p><b>Great Belt Bridge</b>, <u>Dania</u>, <i>6,790 m</i></p>\r\n    </div>\r\n    <div class=\"bridge\">\r\n        <img src=\"./images/Golden Gate Bridge.jpg\" alt=\"Golden Gate Bridge\" />\r\n        <p><b>Golden Gate Bridge</b>, <u>USA</u>, <i>2,737 m</i></p>\r\n    </div>\r\n</div>', 1),
(2, 'about.html', '<section>\r\n    <h2>Nasza Misja</h2>\r\n    <p>Pragniemy dostarczać rzetelne i ciekawe informacje o największych mostach świata, ich typach,\r\n        technologii budowy oraz roli w komunikacji. Chcemy inspirować miłośników inżynierii oraz wszystkich\r\n        zainteresowanych niezwykłymi konstrukcjami.</p>\r\n</section>\r\n<aside>\r\n    <h3>Lista typów mostów</h3>\r\n    <ul>\r\n        <li>Mosty wiszące</li>\r\n        <li>Mosty łukowe</li>\r\n        <li>Mosty belkowe</li>\r\n        <li>Mosty kratownicowe</li>\r\n        <li>Mosty podwieszone</li>\r\n    </ul>\r\n</aside>\r\n<section>\r\n    <h3>Przykładowa tabela rekordów mostowych</h3>\r\n    <table>\r\n        <tr>\r\n            <th>Nazwa</th>\r\n            <th>Kraj</th>\r\n            <th>Długość (m)</th>\r\n        </tr>\r\n        <tr>\r\n            <td>Danyang–Kunshan Grand Bridge</td>\r\n            <td>Chiny</td>\r\n            <td>164800</td>\r\n        </tr>\r\n        <tr>\r\n            <td>Akashi Kaikyō Bridge</td>\r\n            <td>Japonia</td>\r\n            <td>3911</td>\r\n        </tr>\r\n        <tr>\r\n            <td>Great Belt Bridge</td>\r\n            <td>Dania</td>\r\n            <td>6790</td>\r\n        </tr>\r\n    </table>\r\n</section>', 1),
(3, 'bridge_types.html', '<h2>Podstawowe typy mostów</h2>\r\n<table>\r\n    <tr>\r\n        <th>Typ mostu</th>\r\n        <th>Opis</th>\r\n        <th>Przykład</th>\r\n    </tr>\r\n    <tr>\r\n        <td>Most wiszący</td>\r\n        <td>Konstrukcja, w której pomost zawieszony jest na linach lub łańcuchach rozpiętych między wieżami.\r\n        </td>\r\n        <td>Golden Gate Bridge (USA)</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Most belkowy</td>\r\n        <td>Najprostszy typ mostu, składający się z poziomej belki podpartej na końcach.</td>\r\n        <td>Danyang–Kunshan Grand Bridge (Chiny)</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Most łukowy</td>\r\n        <td>Pomost oparty na łuku, który przenosi obciążenia na podpory.</td>\r\n        <td>New River Gorge Bridge (USA)</td>\r\n    </tr>\r\n    <tr>\r\n        <td>Most podwieszony</td>\r\n        <td>Pomost podwieszony na kablach przymocowanych do wysokich pylonów.</td>\r\n        <td>Akashi Kaikyō Bridge (Japonia)</td>\r\n    </tr>\r\n</table>\r\n<p>Każdy typ mostu ma swoje zalety i zastosowania, a wybór konstrukcji zależy od warunków terenowych, długości\r\n    przęsła oraz dostępnych technologii.</p>\r\n<aside>\r\n    <h3>Lista wypunktowana typów mostów</h3>\r\n    <ul>\r\n        <li>Wiszące</li>\r\n        <li>Belkowe</li>\r\n        <li>Łukowe</li>\r\n        <li>Kratownicowe</li>\r\n        <li>Podwieszone</li>\r\n    </ul>\r\n</aside>\r\n<section>\r\n    <h3>Zobacz film o typach mostów</h3>\r\n    <iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/DX_zkaK5PaI?si=Fx9HOUlQaQz8gU3d\"\r\n        title=\"YouTube video player\" frameborder=\"0\" allowfullscreen></iframe>\r\n</section>', 1),
(4, 'gallery.html', '<h2>Galeria największych mostów</h2>\r\n<div class=\"gallery\">\r\n    <div class=\"bridge\">\r\n        <img src=\"./images/Danyang–Kunshan Grand Bridge.jpg\" alt=\"Danyang–Kunshan Grand Bridge\">\r\n        <p>Danyang–Kunshan Grand Bridge, Chiny<br>Długość: 164 800 m</p>\r\n    </div>\r\n    <div class=\"bridge\">\r\n        <img src=\"./images/Akashi Kaikyō Bridge.png\" alt=\"Akashi Kaikyō Bridge\">\r\n        <p>Akashi Kaikyō Bridge, Japonia<br>Długość: 3 911 m</p>\r\n    </div>\r\n    <div class=\"bridge\">\r\n        <img src=\"./images/Great Belt Bridge.jpg\" alt=\"Great Belt Bridge\">\r\n        <p>Great Belt Bridge, Dania<br>Długość: 6 790 m</p>\r\n    </div>\r\n    <div class=\"bridge\">\r\n        <img src=\"./images/Golden Gate Bridge.jpg\" alt=\"Golden Gate Bridge\">\r\n        <p>Golden Gate Bridge, USA<br>Długość: 2 737 m</p>\r\n    </div>\r\n    <div class=\"bridge\">\r\n        <img src=\"./images/Lake Pontchartrain Causeway.jpg\" alt=\"Lake Pontchartrain Causeway\">\r\n        <p>Lake Pontchartrain Causeway, USA<br>Długość: 38 442 m</p>\r\n    </div>\r\n    <div class=\"bridge\">\r\n        <img src=\"./images/Hong Kong–Zhuhai–Macau Bridge.jpg\" alt=\"Hong Kong–Zhuhai–Macau Bridge\">\r\n        <p>Hong Kong–Zhuhai–Macau Bridge, Chiny<br>Długość: 55 000 m</p>\r\n    </div>\r\n    <div class=\"bridge\">\r\n        <img src=\"./images/Vasco da Gama Bridge.jpg\" alt=\"Vasco da Gama Bridge\">\r\n        <p>Vasco da Gama Bridge, Portugalia<br>Długość: 12 345 m</p>\r\n    </div>\r\n    <div class=\"bridge\">\r\n        <img src=\"./images/Runyang Bridge.jpg\" alt=\"Runyang Bridge\">\r\n        <p>Runyang Bridge, Chiny<br>Długość: 35 660 m</p>\r\n    </div>\r\n    <div class=\"bridge\">\r\n        <img src=\"./images/Donghai Bridge.jpg\" alt=\"Donghai Bridge\">\r\n        <p>Donghai Bridge, Chiny<br>Długość: 32 500 m</p>\r\n    </div>\r\n    <div class=\"bridge\">\r\n        <img src=\"./images/San Mateo–Hayward Bridge.jpg\" alt=\"San Mateo–Hayward Bridge\">\r\n        <p>San Mateo–Hayward Bridge, USA<br>Długość: 11 265 m</p>\r\n    </div>\r\n</div>\r\n<aside>\r\n    <h3>Lista wypunktowana mostów z galerii</h3>\r\n    <ul>\r\n        <li>Danyang–Kunshan Grand Bridge</li>\r\n        <li>Akashi Kaikyō Bridge</li>\r\n        <li>Great Belt Bridge</li>\r\n        <li>Golden Gate Bridge</li>\r\n        <li>Lake Pontchartrain Causeway</li>\r\n        <li>Hong Kong–Zhuhai–Macau Bridge</li>\r\n        <li>Vasco da Gama Bridge</li>\r\n        <li>Runyang Bridge</li>\r\n        <li>Donghai Bridge</li>\r\n        <li>San Mateo–Hayward Bridge</li>\r\n    </ul>\r\n</aside>', 1),
(5, 'contact.html', '<h2>Kontakt</h2>\r\n<p>Masz pytania dotyczące największych mostów świata? Chcesz dowiedzieć się więcej o naszej stronie lub podzielić\r\n  się ciekawostką? Wypełnij poniższy formularz, a odpowiemy na Twoje pytania jak najszybciej!</p>\r\n<form action=\"mailto:example@example.com\" method=\"post\">\r\n  <label for=\"name\">Twoje imię:</label><br>\r\n  <input type=\"text\" id=\"name\" name=\"name\" required><br>\r\n  <label for=\"email\">Twój email:</label><br>\r\n  <input type=\"email\" id=\"email\" name=\"email\" required><br>\r\n  <label for=\"message\">Wiadomość:</label><br>\r\n  <textarea id=\"message\" name=\"message\" required></textarea><br>\r\n  <button type=\"submit\">Wyślij</button>\r\n  <button type=\"reset\">Wyczyść</button>\r\n</form>\r\n<aside>\r\n  <h3>Lista kontaktów</h3>\r\n  <ul>\r\n    <li>Redakcja: redakcja@mosty.pl</li>\r\n    <li>Inżynier: inzynier@mosty.pl</li>\r\n    <li>Wsparcie techniczne: wsparcie@mosty.pl</li>\r\n  </ul>\r\n</aside>', 1),
(6, 'scripts.html', '<h2>Skrypty JavaScript</h2>\r\n<div id=\'skrypt_jeden\'>\r\n    <p>Kliknij przycisk, aby zmienić kolor tła strony.</p>\r\n    <form method=\'post\' name=\'background\'>\r\n        <button type=\'button\' onclick=\'changeBackground(\"#FFF000\")\'>Żółty</button>\r\n        <button type=\'button\' onclick=\'changeBackground(\"#000000\")\'>Czarny</button>\r\n        <button type=\'button\' onclick=\'changeBackground(\"#FFFFFF\")\'>Biały</button>\r\n        <button type=\'button\' onclick=\'changeBackground(\"#00FF00\")\'>Zielony</button>\r\n        <button type=\'button\' onclick=\'changeBackground(\"#0000FF\")\'>Niebieski</button>\r\n        <button type=\'button\' onclick=\'changeBackground(\"#FF8000\")\'>Pomarańczowy</button>\r\n        <button type=\'button\' onclick=\'changeBackground(\"#C0C0C0\")\'>Szary</button>\r\n        <button type=\'button\' onclick=\'changeBackground(\"#FF0000\")\'>Czerwony</button>\r\n        <button type=\'button\' onclick=\'changeBackground(getRandomColor())\'>Losowy kolor</button>\r\n    </form>\r\n</div>\r\n<div id=\"skrypt_dwa\">\r\n    <div id=\'zegarek\'></div>\r\n    <div id=\'data\'></div>\r\n    <div id=\'dzienTygodnia\'></div>\r\n</div>', 1),
(7, 'jquery.html', '<h2>jQuery</h2>\r\n<div id=\"animacjaTestowa1\" class=\"test-block\">\r\n    Kliknij, a się powiększe\r\n</div>\r\n<script>\r\n    $(\"#animacjaTestowa1\").on(\"click\", function () {\r\n        $(this).animate({\r\n            width: \"500px\",\r\n            opacity: 0.4,\r\n            fontSize: \"3em\",\r\n            borderwidth: \"10px\"\r\n        }, 1500)\r\n    })\r\n</script>\r\n\r\n<div id=\"animacjaTestowa2\" class=\"test-block\">\r\n    Najedź kursorem. a się powiększe\r\n</div>\r\n<script>\r\n    $(\"#animacjaTestowa2\").on({\r\n        \"mouseover\": function () {\r\n            $(this).animate({\r\n                width: 300\r\n            }, 800)\r\n        },\r\n        \"mouseout\": function () {\r\n            $(this).animate({\r\n                width: 200\r\n            }, 800)\r\n        }\r\n    })\r\n</script>\r\n<div id=\"animacjaTestowa3\" class=\"test-block\">\r\n    Kliknij, abym urósł\r\n</div>\r\n<script>\r\n    $(\"#animacjaTestowa3\").on(\"click\", function () {\r\n        if (!$(this).is(\":animated\")) {\r\n            $(this).animate({\r\n                width: \"+=\" + 50,\r\n                height: \"+=\" + 10,\r\n                opacity: \"+=\" + 0.1,\r\n                duration: 3000\r\n            })\r\n        }\r\n    })\r\n</script>', 1),
(8, 'labor_175036_isi2.php', '<?php\r\n$nr_indeksu = \'175036\';\r\n$nrGrupy = \'ISI2\';\r\n\r\necho \"Krzysztof Krupicki $nr_indeksu $nrGrupy\";\r\necho \"<br>Zastosowanie metody include()<br>\";\r\n\r\ninclude(\'test_include.php\');\r\ntest_include();\r\nrequire_once(\'test_require_once.php\');\r\ntest_require_once();\r\n\r\n?>\r\n<form action=\"labor_175036_isi2.php\" method=\"get\">\r\n    <label for=\"val1\">Podaj liczbę</label>\r\n    <input type=\"number\" name=\"val1\" id=\"val1\">\r\n    <button type=\"submit\">Wyślij</button>\r\n</form>\r\n\r\n\r\n<?php\r\nif(!empty($_GET[\'val1\'])){\r\n    $value = $_GET[\'val1\'];\r\n} else {\r\n    $value = 23;\r\n}\r\nif ($value == 0) {\r\n    echo \"<p>Liczba $value to zero</p>\";\r\n} else if ($value % 2 == 0) {\r\n    echo \"<p>Liczba $value jest parzysta</p>\";\r\n} else {\r\n    echo \"<p>Liczba $value jest nieparzysta</p>\";\r\n}\r\n\r\n\r\necho \"<p>Pętla while<p>\";\r\nwhile ($value > 0) {\r\n    echo \"$value<br>\";\r\n    $value = $value - 3;\r\n}\r\n\r\necho \"<p>Pętla for<p>\";\r\nfor($i = 10; $i!=0; $i--){\r\n    echo \"$i<br>\";\r\n}\r\n\r\n?>\r\n\r\n<form action=\"labor_175036_isi2.php\" method=\"post\">\r\n    <label for=\"val2\">Podaj liczbę</label>\r\n    <input type=\"number\" name=\"val2\" id=\"val2\">\r\n    <button type=\"submit\">Wyślij</button>\r\n</form>\r\n\r\n<?php\r\nif (!empty($_POST[\'val2\'])){\r\n    $value2 = $_POST[\'val2\'];\r\n} else {\r\n    $value2 = rand(0, 10);\r\n}\r\nswitch ($value2) {\r\n    case ($value2 % 2 == 0):\r\n        echo \"<p>$value2 jest podzielne przez 2</p>\";\r\n        break;\r\n    case ($value2 % 3 == 0):\r\n        echo \"<p>$value2 jest podzielne przez 3</p>\";\r\n        break;\r\n    case ($value2 % 5 == 0):\r\n        echo \"<p>$value2 jest podzielne przez 5</p>\";\r\n        break;\r\n    case ($value2 % 7 == 0):\r\n        echo \"<p>$value2 jest podzielne przez 7</p>\";\r\n        break;\r\n    case ($value2 % 9 == 0):\r\n        echo \"<p>$value2 jest podzielne przez 9</p>\";\r\n        break;\r\n    default:\r\n        echo \"<p>Zero dzieli się przez wszystko</p>\";\r\n        break;\r\n}\r\n\r\n\r\nsession_start();\r\nif (!isset($_SESSION[\'visit_counter\'])) {\r\n    $_SESSION[\'visit_counter\'] = 1;\r\n} else {\r\n    $_SESSION[\'visit_counter\']++;\r\n}\r\n\r\necho \"Licznik wizyt: \".$_SESSION[\'visit_counter\'].\"<br>\";\r\n\r\n?>', 1),
(9, 'filmy.html', '<h3>Zobacz film o typach mostów</h3>\r\n<div class=\"video-container\">\r\n    <iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/DX_zkaK5PaI?si=VfS4sx8SyQQuLrYb\"\r\n        title=\"YouTube video player\" frameborder=\"0\"\r\n        allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"\r\n        referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>\r\n</div>\r\n<h3>Zobacz film o największych mostach</h3>\r\n<div class=\"video-container\">\r\n    <iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/v2E-U5tWgeA?si=NVZDaYXG2PydXzRd\"\r\n        title=\"YouTube video player\" frameborder=\"0\"\r\n        allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"\r\n        referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>\r\n</div>\r\n<h3>Zobacz film o budowie mostów</h3>\r\n<div class=\"video-container\">\r\n    <iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/XpTs1V2NQ24?si=wF5LYRh6QpAdcf-e\"\r\n        title=\"YouTube video player\" frameborder=\"0\"\r\n        allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"\r\n        referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>\r\n</div>', 1),
(10, '404', '<h1>404 - Strona Nie Znaleziona</h1>\r\n<p>Przepraszamy, ale strona, której szukasz, nie istnieje.</p>\r\n<p>Możesz wrócić na <a href=\"./\">stronę główną</a> lub sprawdzić inne sekcje.</p>', 1);

--
-- Indeksy dla zrzutów tabel
--

--
-- Indeksy dla tabeli `page_list`
--
ALTER TABLE `page_list`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `page_list`
--
ALTER TABLE `page_list`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
